# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ilyat/Desktop/cpp_STL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ilyat/Desktop/cpp_STL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilyat/Desktop/cpp_STL/CMakeFiles /Users/ilyat/Desktop/cpp_STL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ilyat/Desktop/cpp_STL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bst_lib

# Build rule for target.
bst_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bst_lib
.PHONY : bst_lib

# fast build rule for target.
bst_lib/fast:
	$(MAKE) $(MAKESILENT) -f containers/bst/CMakeFiles/bst_lib.dir/build.make containers/bst/CMakeFiles/bst_lib.dir/build
.PHONY : bst_lib/fast

#=============================================================================
# Target rules for targets named bst_main

# Build rule for target.
bst_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bst_main
.PHONY : bst_main

# fast build rule for target.
bst_main/fast:
	$(MAKE) $(MAKESILENT) -f containers/bst/CMakeFiles/bst_main.dir/build.make containers/bst/CMakeFiles/bst_main.dir/build
.PHONY : bst_main/fast

#=============================================================================
# Target rules for targets named hashmap_lib

# Build rule for target.
hashmap_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashmap_lib
.PHONY : hashmap_lib

# fast build rule for target.
hashmap_lib/fast:
	$(MAKE) $(MAKESILENT) -f containers/hashmap/CMakeFiles/hashmap_lib.dir/build.make containers/hashmap/CMakeFiles/hashmap_lib.dir/build
.PHONY : hashmap_lib/fast

#=============================================================================
# Target rules for targets named hashmap_main

# Build rule for target.
hashmap_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hashmap_main
.PHONY : hashmap_main

# fast build rule for target.
hashmap_main/fast:
	$(MAKE) $(MAKESILENT) -f containers/hashmap/CMakeFiles/hashmap_main.dir/build.make containers/hashmap/CMakeFiles/hashmap_main.dir/build
.PHONY : hashmap_main/fast

#=============================================================================
# Target rules for targets named linked_list_lib

# Build rule for target.
linked_list_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linked_list_lib
.PHONY : linked_list_lib

# fast build rule for target.
linked_list_lib/fast:
	$(MAKE) $(MAKESILENT) -f containers/linked_list/CMakeFiles/linked_list_lib.dir/build.make containers/linked_list/CMakeFiles/linked_list_lib.dir/build
.PHONY : linked_list_lib/fast

#=============================================================================
# Target rules for targets named linked_list_main

# Build rule for target.
linked_list_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linked_list_main
.PHONY : linked_list_main

# fast build rule for target.
linked_list_main/fast:
	$(MAKE) $(MAKESILENT) -f containers/linked_list/CMakeFiles/linked_list_main.dir/build.make containers/linked_list/CMakeFiles/linked_list_main.dir/build
.PHONY : linked_list_main/fast

#=============================================================================
# Target rules for targets named string_lib

# Build rule for target.
string_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 string_lib
.PHONY : string_lib

# fast build rule for target.
string_lib/fast:
	$(MAKE) $(MAKESILENT) -f containers/string/CMakeFiles/string_lib.dir/build.make containers/string/CMakeFiles/string_lib.dir/build
.PHONY : string_lib/fast

#=============================================================================
# Target rules for targets named string_main

# Build rule for target.
string_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 string_main
.PHONY : string_main

# fast build rule for target.
string_main/fast:
	$(MAKE) $(MAKESILENT) -f containers/string/CMakeFiles/string_main.dir/build.make containers/string/CMakeFiles/string_main.dir/build
.PHONY : string_main/fast

#=============================================================================
# Target rules for targets named vector_lib

# Build rule for target.
vector_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vector_lib
.PHONY : vector_lib

# fast build rule for target.
vector_lib/fast:
	$(MAKE) $(MAKESILENT) -f containers/vector/CMakeFiles/vector_lib.dir/build.make containers/vector/CMakeFiles/vector_lib.dir/build
.PHONY : vector_lib/fast

#=============================================================================
# Target rules for targets named vector_main

# Build rule for target.
vector_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vector_main
.PHONY : vector_main

# fast build rule for target.
vector_main/fast:
	$(MAKE) $(MAKESILENT) -f containers/vector/CMakeFiles/vector_main.dir/build.make containers/vector/CMakeFiles/vector_main.dir/build
.PHONY : vector_main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bst_lib"
	@echo "... bst_main"
	@echo "... hashmap_lib"
	@echo "... hashmap_main"
	@echo "... linked_list_lib"
	@echo "... linked_list_main"
	@echo "... string_lib"
	@echo "... string_main"
	@echo "... vector_lib"
	@echo "... vector_main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

